pipeline:
  name: Visa Information Monitoring
  identifier: visa_monitoring
  projectIdentifier: master_application
  orgIdentifier: default
  tags:
    visa: "true"
    monitoring: "true"
  
  properties:
    ci:
      codebase:
        connectorRef: github_connector
        repoName: personal-publicdata
        build: <+input>
  
  stages:
    - stage:
        name: Visa Monitor
        identifier: visa_monitor
        description: Monitor visa information pages for changes
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run Visa Monitor
                  identifier: run_visa_monitor
                  spec:
                    shell: Bash
                    command: |
                      #!/bin/bash
                      set -e
                      
                      echo "=== Installing Dependencies ==="
                      pip install -r requirements.txt
                      playwright install chromium
                      
                      echo "=== Creating Required Directories ==="
                      mkdir -p logs
                      
                      echo "=== Running Visa Monitor ==="
                      python monitoring/visa_monitor.py
                    envVariables:
                      NOTIFICATION_WEBHOOK: <+secrets.getValue("notification_webhook")>
                  timeout: 30m
              
              - step:
                  type: Run
                  name: Commit Changes
                  identifier: commit_changes
                  spec:
                    shell: Bash
                    command: |
                      #!/bin/bash
                      
                      echo "=== Configuring Git ==="
                      git config --local user.email "harness@automation.com"
                      git config --local user.name "Harness Automation"
                      
                      echo "=== Setting up GitHub authentication ==="
                      git config --local credential.helper store
                      echo "https://${GITHUB_TOKEN}@github.com" > ~/.git-credentials
                      
                      echo "=== Staging changes ==="
                      git add reports/status_history/visa_hashes/ || true
                      git add reports/monitoring_reports/ || true
                      git add source_data/visa_requirements.yml || true
                      
                      if git diff --staged --quiet; then
                        echo "✅ No changes to commit"
                      else
                        echo "=== Committing changes ==="
                        git commit -m "🛂 Update visa monitoring [Harness automated]"
                        
                        echo "=== Pushing to GitHub ==="
                        git push origin main || {
                          echo "⚠️ Push failed, but continuing pipeline"
                          exit 0
                        }
                        
                        echo "✅ Changes pushed successfully"
                      fi
                    envVariables:
                      GITHUB_TOKEN: <+secrets.getValue("github_token")>
                  timeout: 10m
        tags: {}
  
  triggers:
    - trigger:
        name: Weekly Schedule
        identifier: weekly_schedule
        enabled: true
        description: Run every Monday and Thursday
        type: Cron
        spec:
          type: Cron
          spec:
            expression: "0 0 * * 1,4"  # Monday and Thursday at midnight UTC
            inputYaml: |
              pipeline:
                identifier: visa_monitoring

